### ISSUE TITLE
BREAK BLOCK

### ISSUE THREAD

**Issue by RangeBanenge** [Ordwen/ODailyQuests#23]
I have such a problem, I break the blocks that are needed for the quest, but they are not protected.
Maybe I need to break blocks placed by other players?
quests:
  1:
    name: "&eWool lover"
    menu_item: WHITE_WOOL
    description:
      - " "
      - "&fExercise: &7Get 64 wool"
      - " "
      - "&e» &fReward: &a5000 XP"
    quest_type: BREAK
    required_item: 
      - RED_WOOL
      - WHITE_WOOL
      - BLUE_WOOL
      - GREEN_WOOL
      - YELLOW_WOOL
      - LIME_WOOL
      - BLACK_WOOL
      - ORANGE_WOOL
    required_amount: 64
    reward:
      reward_type: COMMAND
      commands:
        - "alonsolevels addexp %player% 5000"

**Comment by Ordwen** [comment]
I'm not sure I understand. But if you break blocks that you've just placed, it's normal for them not to be counted if the `store_placed_blocks` option is enabled in the config (and it is by default). You can deactivate the option, reload the plugin, and reactivate it when you've finished your tests.

**Comment by RangeBanenge** [comment]
Ok, thanks
