### ISSUE TITLE
Remove unnecessary spam from console

### ISSUE THREAD

**Issue by Dagrond** [Ordwen/ODailyQuests#26]
I really don't need these messages on each time a player joins/quits server. Please add an option to disable them. They are spamming console on higher player counts.
![image](https://github.com/Ordwen/ODailyQuests/assets/30177675/57e3edeb-a6b2-4a35-b993-9844cebb3824)

**Comment by Ordwen** [comment]
This will be possible in the next update, which I will publish within 2-3 weeks.

**Comment by Ordwen** [comment]
Added in 2.2.4
