### ISSUE TITLE
[Feature Request] Money should allow double, not only integer

### ISSUE THREAD

**Issue by Folas1337** [Ordwen/ODailyQuests#27]
I realized I can not reward players with just $0.25 cause apparently that means I'll get $0 which gives me the impression it's limited to integers.

I'd like to be able to reward amounts smaller than $1 and also more precise than just integers.

If you need more information, let me know.

Thanks in advance!

**Comment by Folas1337** [comment]
Also if anyone comes across the same issue, you can obviously use the command and then do something like "money give 0.25 %player%" but then if you ever switch money plugins and it uses another syntax, you gotta change it for all quests.

**Comment by Medved0546** [comment]
you can press ctrl + h in notepad and replace for example money give with pp give it does not require replacing each quest separately
and maybe adding fractions can cause some bugs..

**Comment by Ordwen** [comment]
> I realized I can not reward players with just $0.25 cause apparently that means I'll get $0 which gives me the impression it's limited to integers.
> 
> I'd like to be able to reward amounts smaller than $1 and also more precise than just integers.
> 
> If you need more information, let me know.
> 
> Thanks in advance!

It should already be the case, sorry about that. I'll fix it in the next update.

**Comment by Folas1337** [comment]
I realized that for some reason XConomy with Towny doesn't seem to accept doubles/fractions, I'm not entirely sure why. It might also be why it didn't work for me in this instance, so apologies if that's the case and feel free to close this issue if that's the case.
