### ISSUE TITLE
Duplicate quest rewards on "type quests: CRAFT"

### ISSUE THREAD

**Issue by LOURENT4462** [Ordwen/ODailyQuests#37]
📍 Description
for example, on my server there is a mission to make 1x shulker box, the player prepares more than 2 shulker shells, then uses the craft all keybind, it will make many shulker boxes (more than 1), and strangely odailyquest gives multiple rewards according to the number of shulkers made. craft by player 0-o

📍 Reproduction Steps
1. make a craft quest 1x shulker
2. prepare the materials to make shulker (more, maybe if 1 shulker requires 2 shulker shells, we will prepare more than that)
3. Then go to the crafting table and use the keybind to craft everything
4. and boom, you will get a quest reward multiplied by 0-o

📍 Version
Server: Paper version git-Paper-307 (MC: 1.20.2)
Plugin: ODailyQuests-2.2.3

**Comment by Ordwen** [comment]
> 📍 Description for example, on my server there is a mission to make 1x shulker box, the player prepares more than 2 shulker shells, then uses the craft all keybind, it will make many shulker boxes (more than 1), and strangely odailyquest gives multiple rewards according to the number of shulkers made. craft by player 0-o
> 
> 📍 Reproduction Steps
> 
>     1. make a craft quest 1x shulker
> 
>     2. prepare the materials to make shulker (more, maybe if 1 shulker requires 2 shulker shells, we will prepare more than that)
> 
>     3. Then go to the crafting table and use the keybind to craft everything
> 
>     4. and boom, you will get a quest reward multiplied by 0-o
> 
> 
> 📍 Version Server: Paper version git-Paper-307 (MC: 1.20.2) Plugin: ODailyQuests-2.2.3

Hello, sorry for the late answer. Can you try with the [latest plugin version](https://www.spigotmc.org/resources/odailyquests-daily-quests-plugin-1-16-1-20.100990/) and tell me if it's fixed or not?

**Comment by Ordwen** [comment]
Perfect, thank you!
