### ISSUE TITLE
Can you allow people to push to separate branches so I can open a pr with some bug fixes I did

### ISSUE THREAD

**Issue by 777Ricky** [Ordwen/ODailyQuests#4]
Can you allow people to push to separate branches so I can open a pr with some bug fixes I did

**Comment by Ordwen** [comment]
Hey, can't you make one? Normally it's possible, by the way, someone else made one (the first one) today...

**Comment by 777Ricky** [comment]
I guess I could fork it but it would be far easier to just push a separate branch so I don't have to fork it all I did was add ignoreCancelled = true for quest progression events that are cancellable

**Comment by Ordwen** [comment]
I've been looking for it, but I don't think it's possible without adding you as a contributor... 

I can create branch restrictions but if I understand correctly you still have to be a collaborator to interact with it, and the only way to make a pull request without being a collaborator is to make a fork
