### ISSUE TITLE
When the player completes all global missions, the reward is not triggered

### ISSUE THREAD

**Issue by mxlt02** [Ordwen/ODailyQuests#56]
When the player completes all global missions, the reward is not triggered. However, it can be triggered automatically after the task is forcibly completed by an administrator command

# Global Reward
# Will be given when the player has completed all his daily quests.
# The syntax is the same as for quest rewards.
global_reward:
  enabled: true
  reward_type: COMMAND
  commands:
  - points give %player% 100
  - levels addexp %player% 800
  - mi give material ADVENTURER_BADGE %player%

paper1.20.4 ODQ  2.2.5

**Comment by Ordwen** [comment]
Hello, can you try with [this version](https://github.com/Ordwen/ODailyQuests/releases/download/SNAPSHOT/ODailyQuests-2.3.0-SNAPSHOT-7.jar) please?

**Comment by mxlt02** [comment]
> Hello, can you try with [this version](https://github.com/Ordwen/ODailyQuests/releases/download/SNAPSHOT/ODailyQuests-2.3.0-SNAPSHOT-7.jar) please?

I tried the latest version 2.3.0-SNAPSHOT-10 and the issue has been fixed, thanks for your great work
