### ISSUE TITLE
i meet some problems when i an playing this on a purpur server

### ISSUE THREAD

**Issue by jdz-green** [Ordwen/ODailyQuests#58]
i would like to ask the developer sincerely that what is a Saint Cobblestone!!!

**Comment by Ordwen** [comment]
> i would like to ask the developer sincerely that what is a Saint Cobblestone!!!

Hello, the Saint Cobblestone is just an example item of how you can ask for custom items in a quest, as [described here](https://ordwenplugins.gitbook.io/odailyquests/quests/create-a-quest#custom-items) in the Wiki.
