### ISSUE TITLE
O'DailyQuests: Error in CraftMetaSkull.setProfile causing plugin malfunction

### ISSUE THREAD

**Issue by thisisaef** [Ordwen/ODailyQuests#63]
**Describe the bug**
When the O'DailyQuests plugin is loaded, an error is thrown related to CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile). This seems to occur when custom player heads are used in quests, preventing proper functionality.

**Expected Behavior**
The plugin should handle the custom player heads in quests without throwing errors, allowing the quests to load and function as intended.

**Actual Behavior**
An error occurs in the server logs, and the affected quests do not work as expected. Specifically, the following error is logged:
`org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile)`

**Steps to Reproduce**
1. Install the O'DailyQuests plugin.
2. Configure a quest that includes custom player heads as rewards or objectives.
3. Start the server and observe the error in the logs.

**Log**
latest.log: https://paste.helpch.at/rebuvurido.makefile

**Plugin List**
ODailyQuests-2.3.0-SNAPSHOT-16

**Software brand**
Backend: Paper 1.21.1-110-master@6d7a438 (MC: 1.21.1)

**Additional Information**
The issue may be related to custom player heads and could be caused by changes in how Minecraft handles player profile data. Other plugins such as EcoEnchants are also throwing unrelated errors.

**Comment by Ordwen** [comment]
Hello, can you please try with [this snapshot](https://github.com/Ordwen/ODailyQuests/releases/tag/2.3.0-SNAPSHOT)? It should be fixed, let me know. Sorry for the wait!

**Comment by thisisaef** [comment]
It works fine now and no problem. Thanks for developing such a great plugin.

**Comment by Ordwen** [comment]
Thank you so much!
